### ISSUE TITLE
add info about yaml default branch assuming main to docs

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck#135]
(or detect default branch in `use_...`)

**Comment by mpadge** [comment]
@grwhumphries The above commit is a partial fix for your problems - running `use_github_actions_pkgcheck()` will now construct a check for whatever branch you are currently in when you run the function.

## TODO:

- [ ] Document this, primarily via a single statement that the workflow defaults to current branch

@assignUser: The whole system works fine locally in any branch at all, but when run remotely by and for the @ropensci-review-bot, the branch is hard-coded to the default branch set on github, and there is currently no way around this. My suggestion to enable checks to be run from arbitrary branches would be for you to first enable a yaml parameter to define an arbitrary branch in `pkgcheck-action`, and for that to be used to override current default behaviour only if and where it is specified. That means anyone wanting checks to be run on non-default branches could and would have to have an action in the repo which specified the branch. Thoughts? If you approve, could you please open an issue in `pkgcheck-action`, ping me there, and once that's done, I'll continue over here. Or feel free to suggest any alternative approach. Thanks! And thanks @grwhumphries for raising this useful enhancement :smile:

**Comment by assignUser** [comment]
@mpadge 
> a yaml parameter to define an arbitrary branch in `pkgcheck-action`

This parameter already exists :wink: :
```yaml
on:
  push:
    branches:
      - main
      - other_branch
      - dev_branch
```
Like locally, `pkgcheck` will be run on the currently checked out branch by default. So I don't think it is necessary to implement this within the action/pkgcheck. If you want to make the review-bot more flexible I would say that is something best taken care of within the bot api?

**Comment by assignUser** [comment]
We could of course add a `branch = default_branch()` arg to the `use_` action which adds them to the branches array?

**Comment by mpadge** [comment]
Yeah, thanks @assignUser, i realised in the meantime that you'd already built that in, which is great. And i guess that adding a `branch` parameter would be the best way to document this, because that puts the parameter "up front" for all to see. We can just use `branch = gert::git_branch()` for current branch. Thanks.

**Comment by mpadge** [comment]
That implements all of the above, but needs to be re-opened because there are still a few functions using [the `get_github_default_branch()` function](https://github.com/ropensci-review-tools/pkgcheck/blob/66b53c1598929a72391200dc5872415bc0d9c5ff/R/github.R#L89-L114). The result of this also needs to be re-mapped to any values specified in `pkgcheck` yaml actions, if given.
