### ISSUE TITLE
Statistical standards are missing

### ISSUE THREAD

**Issue by schneiderpy** [ropensci-review-tools/pkgcheck#162]
Hello,

currently I am running into the same issue: while running pkgcheck on github (but has also the new github-action), the check does not pass due to the following error: 
Tracing function "install.packages" in package "utils"
✔ Enabled colors!
Install dependencies
Running Pkgcheck...
Error: Statistical standards are missing

> srr_stats_pre_submit()
√ All applicable standards [v0.1.0] have been documented in this package (56 complied with; 46 N/A standards)
The srr-standards file is located in the R/folder (with all other R-files)
The pkgcheck - check passed about two month ago, but since the srr-standards file it doesn't ... no idea why

**Comment by schneiderpy** [comment]
Adding the log file .... 
[logs_191.zip](https://github.com/ropensci-review-tools/pkgcheck/files/9768049/logs_191.zip)

**Comment by schneiderpy** [comment]
Hello @mpadge. Could you find out what might have caused the error / bug?

**Comment by mpadge** [comment]
Sorry @schneiderpy, shall do first  thing tomorrow morning. Thanks for being patient

**Comment by schneiderpy** [comment]
No problem @mpadge

**Comment by mpadge** [comment]
This is actually working as it should, although admittedly in a way that even i found very confusing. The error is because there are standards missing from your code:

``` r
path <- gert::git_clone ("https://github.com/schneiderpy/concstats")
srr::srr_stats_pre_submit (path)
#> ! Package can not be submitted because the following standards [v0.1.0] are missing from your code:
#> 1. EA1.0
#> 2. G1.0
#> 3. G1.1
```

<sup>Created on 2022-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is, however, not clearly stated in the general `pkgcheck` report at all. You can currently only see this information by:

``` r
library (pkgcheck)
checks <- pkgcheck (path)
md <- checks_to_markdown (render = TRUE)
```

If you then click on the "report of author-reported standards compliance", you'll see way at the bottom the details of missing standards.

## TODO

- [ ] Fix Initial statement in check report so it prints actual missing standards
- [ ] Move information on any missing standards to top of report, rather than at the bottom.

**Comment by mpadge** [comment]
@schneiderpy those changes should make things much clearer now.Thanks for picking that up!
