### ISSUE TITLE
Add nix to Dockerfile

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck#195]
@b-rodrigues This issue is to document whether or not nix can be added to our build system (https://github.com/ropensci/software-review/issues/624). The only potential reason not to do so is image size. It seems that adding nix can greatly inflate image sizes, so we'll have to do some tests to see how big ours becomes. You'll see all developments here.

**Comment by mpadge** [comment]
@b-rodrigues Adding nix install to our build container adds "only" 120MB. Not too large, but nevertheless not tiny. I'll check out our current server config and get back to you. Before we do this, can you please explain here what effect this might have on checks for your {nix} package? I've seen the current checks on the thread, with 36.7% coverage. How much could that be increased if we had nix on our system? (And in case it affects your tests: It would be a non-systemd install.)

**Comment by b-rodrigues** [comment]
Here is the current status as of now: covr doesn’t run at all at the moment, neither on a system with Nix installed or not. We had some issues with some tests on Ubuntu specifically, and were able to solve them: so now `devtools::test()` passes on any operating system, and whether Nix is available or not (for tests that require Nix, we have use a "skip if nix is not available" function on systems where Nix is not available), and also whether R itself was installed using Nix or not. So essentially, every configuration works.

But now covr just fails, even in "classic" environments where Nix isn’t available. Even adding `skip_on_covr()` in the tests that are problematic doesn’t help. You can see it here: https://github.com/b-rodrigues/rix/actions/runs/7788051416/job/21236628194

@philipp-baumann did some digging and found out that `covr` essentially runs `tools::testInstalledPackage()`. Just running `tools::testInstalledPackage()` also works: so there’s something that `covr()` does with environment variables or such that make the tests fail. `with_nix()` and `nix_build()` set environment variables to make sure the runtime is pure, and there’s probably something going on with `covr` that nullifies what we do to make `with_nix()` and `nix_build()` work.

To specifically answer your question, we don’t know what the coverage would be if everything worked with `covr`, but a guesstimate would around 50%. `with_nix()` and `nix_build()` together are around 800 LOCs (without comments). We also included new tests since then, and so the coverage would be higher still. However, I’m not sure if it would be worth it to install Nix on your build container as long as we aren’t able to make `covr` work even with Nix unavailable.

Have you perhaps encountered a similar issue in the past, where `covr` failed even though `devtools::test()` works?

**Comment by mpadge** [comment]
Oh yeah, there are lots of `covr` quirks. The whole thing works by injecting symbols into your own code, and to do this is has to create an isolated clone of the repo before testing it. It then relies on complicated system commands [like this](https://github.com/r-lib/covr/blob/54de614f5c17a42bfaef2c87dbf5723ca701326a/R/icc.R#L96-L103). Very difficult to debug in environments like yours, but likely the simple fact that covr relies on system commands outside R processes will prevent you being able to successfully run it within a nix process.

That said, i'd be happy to help any way i might be able. Plus we can definitely pre-install nix if we get that far, so that's good news at least.

**Comment by philipp-baumann** [comment]
@mpadge Thanks a lot for further checking out ROpenSci containers with Nix. 

Glad you can confirm that there are a lot of tweaks.

As Bruno explained, I was looking into where failures in with `covr::package_coverage()` for `nix_build()` and `with_nix()` could come from, both on macOS and on a Ubuntu 22.04 VM. `covr::package_coverage` collates the library paths:

```r
# local machine 
install_path = covr:::temp_file("R_LIBS")
libs <- covr:::env_path(install_path, .libPaths())
# e.g. something like this on macOS
# [1] "/private/var/folders/47/c2r7jpcs7dl3jgy_8yb398kw0000gn/T/RtmpyckL1j/R_LIBSe84a4b0d02f9:/Users/philipp/Library/R/arm64/4.3/library:/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library"
```

I was first suspecting the `.libPaths()` resetting by covr collation mechanism was resposible (`withr::...`) . First here https://github.com/r-lib/covr/blob/54de614f5c17a42bfaef2c87dbf5723ca701326a/R/covr.R#L465-L473 and then when calling `tools::testInstalledPackage()` here https://github.com/r-lib/covr/blob/54de614f5c17a42bfaef2c87dbf5723ca701326a/R/covr.R#L487-L488

 But`nix_build()` is relatively simple and is essentially a `nix-build` wrapper for `sys::exec_internal()` or `sys::exec_background()` for a directory containing a `default.nix` with the Nix expression to build. https://github.com/b-rodrigues/rix/blob/3be2ecbef4cd14e5dfffe695b9be26ba334bc0a7/R/nix_build.R#L80-L95 

It all works fine in devtools::test() for this. We even force the Nix store into the `PATH` also in the test, where `nix-build` CLI gets picked up. => https://github.com/b-rodrigues/rix/blob/3be2ecbef4cd14e5dfffe695b9be26ba334bc0a7/tests/testthat/test-with_nix.R#L7 

Do you maybe have any further ideas why `nix_build()` covr tests even fail (`with_nix()` does a bit more stuff? Usually `nix_build()` as well as `with_nix()` tests fail with exit status 1 (from {sys}; can't further debug) or 147 (segmentation fault).
