### ISSUE TITLE
Strange error message regarding MASS when trying to run pkgcheck.

### ISSUE THREAD

**Issue by sjentsch** [ropensci-review-tools/pkgcheck#199]
When trying to run pkgcheck (as a GitHub action, [using this yaml-file](https://github.com/sjentsch/jmvReadWrite/blob/main/.github/workflows/pkgcheck.yaml)) , I get an error message indicating that MASS can't be installed (and that it needs two different versions of R).

```
* jmv: Can't install dependency MASS
  * MASS: Needs R >= 4.4.0
  * MASS: Needs R >= 4.5
```

Is this an error or am I doing something wrong?

**Comment by mpadge** [comment]
It's a temporary error because the default GitHub runners are [still on R4.3.3](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) but download latest versions of all packages. The `Matrix` package recently  introduced [breaking changes](https://cran.r-project.org/web/packages/Matrix/news.html) and so the latest version has `Depends: R >= 4.4.0`. The `MASS` package has a strong dependency on `Matrix` and also introduced this. That means latest packages on current latest GitHub runners fail if they require `Matrix` in any way.

Easy solution: Wait and it will solve itself.
Less easy but immediate solution: hard-code the R version:
```
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
```
We'd need to to that on our side, and then keep an eye out for when GH upgrades their side. Thoughts @assignUser?

**Comment by assignUser** [comment]
@mpadge Wow, pretty disruptive move by {Matrix}...
Yeah I think using `setup-r` is a good idea, though you don't have to hard-code the version, the action will get 4.4 and setup the libraries etc. (I usually run the action with `install-r: false` even when I don't need anything specific for that reason): https://github.com/assignUser/test-repo-a/actions/runs/8963768517/workflow

**Comment by sjentsch** [comment]
@mpadge Thanks for your help and the recommendation, but I did not manage with the code snippet you sent. I will just wait that it's solved on your side. It's not too serious. Thanks again!

**Comment by mpadge** [comment]
@sjentsch Try the code linked from @assignUser above - that should ensure that the appropriate version of MASS is intalled. Otherwise it shouldn't take long for GitHub to catch up to R4.4 and then the problem will disappear.

**Comment by mpadge** [comment]
GitHub runners have caught up now, so this should all be fixed

**Comment by sjentsch** [comment]
Yes, all works fine now. Thanks for your effort!
