### ISSUE TITLE
A question on naming

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#46]
There are e.g.

* `pkgchk_has_scrap` which when it's the case, is bad;
* `pkgchk_has_contrib` which when it's the case, is good.

Should there be some sort of alignment of names?

**Comment by mpadge** [comment]
I know what you mean, but think that the comments in [this previous commit](https://github.com/ropensci-review-tools/pkgcheck/commit/2035fa1ac229fa1f601ee47ec4ef87fa77f574f0) are still valid. Consistency in the sense you're suggesting would require tests to be named in negative form - like former `has_no_scrap`, leading to  the double-negative of `if (!has_no_scrap)`. I think double negatives are more confusing than the non-alignment you highlight, but am open to being convinced otherwise ...?

**Comment by maelle** [comment]
yeah it might require some complicate naming (`is_scrapfree()`) for little gain :sweat_smile:

**Comment by mpadge** [comment]
Yes, plus i'm quite attached to the `pkgchk_has_` nomenclature for stuff which packages should have. In that context, i think potential negative/positive confusion is a relatively small price to pay. Close for now?

**Comment by maelle** [comment]
ok!
