### ISSUE TITLE
Refactor formatting for _md helpers?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#48]
So that instead of having

```
c ("",
       paste0 (symbol_crs (),
               " Package contains no vignette."),
       "")
``` 

One could just return the actual info, and something else would add the empty lines.

**Comment by mpadge** [comment]
The empty lines are really important, because when the whole thing is converted to HTML by being dumped as a single character string in a GitHub issue, lack of empty lines causes continuation of preceding HTML environments like tables and the like. And the only direct way to ensure those are broken is to ensure every component is embedded in `""`. Especially once it's easy to add new tests, we'll never know what might come before or after a test, so can't rely on ability to insert appropriate empty lines at any other stage.

I totally see your point, but see this as a special case, because all of these `_md` helpers work to construct a single character string the contents of which can not (or ought not!) be examined at any point during it's construction. Or in other words: the only context for knowing whether or not a string should be embedded in "" or not is the local context in which it is being constructed. Once any function is returned from, that context is lost, we only have a now-longer string, and no way of knowing for sure whether extra lines are needed. Does that make sense?

**Comment by maelle** [comment]
it does, I just wish there could be an easier way to indicate lines and then something else would add the "".

**Comment by mpadge** [comment]
I'll leave this issue open to have a bit more of a think about it. Watch this space - even if only for an eventual, "sorry, nope". but hopefully something better than that!

**Comment by mpadge** [comment]
With the major changes around #40, those lines are now buried deep within one single function only:

https://github.com/ropensci-review-tools/pkgcheck/blob/8617ec2ca94b509df941bb091e45e6ae17c8c4ef/R/pkgcheck-methods.R#L218-L235

All of these `_md` rendering methods now rely on that generic function, so I think this can be closed now.
