### ISSUE TITLE
Improve the check for vignettes

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#56]
We should check the vignette is an HTML one but it's not that easy as the output format might be in the vignette itself or in a `_site.yml`.

**Comment by maelle** [comment]
Related https://github.com/rstudio/rmarkdown/issues/2213

**Comment by mpadge** [comment]
I'm very pleased that you submitted #58, because i didn't really know how best to address this, so thank you very much for that! One important question though: Does this really work?

``` r
# in pkgcheck directory:
rmarkdown::default_output_format(file.path(here::here(), "README.Rmd"))$name
#> [1] "md_document"
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

... But `pkgdown` still renders it perfectly as `html`. I think we still need to improve the diagnosis here ... :question:

**Comment by maelle** [comment]
pkgdown's rendering of vignettes to html is independent from the output format except if you use the `as_is` option.
Furthermore, your example is the README, that pkgdown transforms to HTML (without knitting it at the moment).

**Comment by mpadge** [comment]
I'll happily misquote myself here:

> i ~~didn't~~don't really know how best to address this

... And am more than happy to leave it to your expertise. Is #58 good to merge then?

**Comment by maelle** [comment]
I think so. However I was wondering whether it'd be possible to create the infrastructure to test such things.

* helper function for creating a local temporary package.
* some code to tweak it to make it fail one of the requirements.
* snapshot test.

What do you think?

**Comment by mpadge** [comment]
Yes, that would be really useful. I use [`srr::srr_stats_pkg_skeleton()`](https://docs.ropensci.org/srr/reference/srr_stats_pkg_skeleton.html) for [skeleton tests here](https://github.com/ropensci-review-tools/pkgcheck/blob/main/tests/testthat/test-pkgcheck.R#L5). If you run as is, it is identified as an `srr` package so pulls those checks in yet fails because the skeleton is incomplete. That should make it very easy, right?

**Comment by mpadge** [comment]
Re-opened to address a rogue check here:

![image](https://user-images.githubusercontent.com/6697851/133967333-80e6c4b3-817d-4244-b65f-73e120905efd.png)

It also appears up the top where it should. Just have to remove that latter one
