### ISSUE TITLE
Could pkgstats parse dependencies?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/pkgcheck#72]
I.e. each column would be not a string but instead a list to make it easier to retrieve the vector of deps.

**Comment by mpadge** [comment]
Moved to `pkgcheck` because dependencies can indeed be parsed here. The main object returned by `pkgcheck` currently does not have a list of dependencies, but that would be both good and important to include. @maelle My suggestion will be to add an extra item to the main `pgkcheck()` output called `"description"`, that has parsed values of the main `pkgstats()$desc` output:

``` r
library (pkgstats)
path <- "/<path>/<to>/lme4_1.1-26.tar.gz"
s <- pkgstats (path)
s$desc
#>   package version                date    license                          urls
#> 1    lme4  1.1-26 2020-12-01 00:50:10 GPL (>= 2) https://github.com/lme4/lme4/
#>                                  bugs aut ctb fnd rev ths trl depends
#> 1 https://github.com/lme4/lme4/issues   4   9   0   0   0   0  Matrix
#>                                                                                       imports
#> 1 graphics, grid, splines, utils, parallel, MASS, lattice, boot, nlme, minqa, nloptr, statmod
#>                                                                                                                        suggests
#> 1 knitr, rmarkdown, PKPDmodels, MEMSS, testthat, ggplot2, mlmRev, optimx, gamm4, pbkrtest, HSAUR3, numDeriv, car, dfoptim, mgcv
#>        linking_to
#> 1 Rcpp, RcppEigen
```

<sup>Created on 2021-09-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

That info is not part of any actual check, but is pretty important meta-information that can and should be stored with the `pkgcheck` output regardless.

**Comment by maelle** [comment]
Or it could be a desc object? (not sure it's a good suggestion at all).
